language: node_js
node_js:
  - "4.3.2"
cache:
  directories:
  - node_modules
  - bower_components

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
  - node ./node_modules/protractor/bin/webdriver-manager update --standalone
  - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start --standalone 2>&1 &"
  - sleep 5

script:
  - echo "running tests"
  - grunt test
  - grunt protractor-firefox
