language: node_js
node_js:
  - "4.3.2"
cache:
  directories:
  - node_modules
  - bower_components

before_install:
  before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - sleep 3 # give xvfb some time to start
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
  - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start --standalone 2>&1 &"
  - sleep 5

script:
  - echo "running tests"
  - grunt # build and run unit tests
  - grunt protractor-firefox # run e2e tests
