language: node_js

node_js:
  - "4.3.2"

cache:
  directories:
    - node_modules
    - bower_components

env:
  global:
    - secure: "bpCnkolAyhiEe/X+lbuwgAerO44Depp33eQWE/YDjlQGwOoGR50Ee0WY4Mw3qDQZHX/T21OTU3XOkKOwxR61o8gZcNS/5SfV/b8gjcvyaXIFdQXbqs1BNiysVxoRpIWO8Fdj5bCOUOLUHWNg46whF7va+2+5767FWNoRYLSu9iuIgbqxNiHEiuWZe/7eBsbOrKouLmWXBB224j7Y8V8Eigf6ImsziMy8U/+bjJ7v7fBqjbg3+YR0aSBbfRyNvEcAua0QqG0MicSXXP6E9BLaoEb1/MeanxFHX3SzgODY0DDRXX4XcwCbARZsNY7U9R2Jhq5zMQZq7k5kcCyfll6a2mXSjDR0xY7AM5pA7XG4qTIwK/jWJU9mGrSdyUizYwcWiML1444gs+7OFRYwEMPF2hJb6jAqL0g1N1aKFavGHKU1RFflIGn5x8VHTo+a/GYf91bWTeJaaIYpocWZoA4Tzqv9X750DSrt6QJSHSTZwzDgoVltTvF5GvZvAiGkL/EESVzWq0WWsfSBbMTj8ygxK9pLf0eR7mI2M78M2pF9nX0FMqnYigI06BtIRwJuvQCFpl8EzVPLyNigq1T+Vttc32G4FlqSlN6aGEOFv71CZwQiRlTinIl0OXZ3kIvTy9Dw/EkAO5ixeQqnhl7W5SLR8zpeOFNyBnoDcAr8RbYcJUs="
    - secure: "gC649yQGKz5JN2+xTuQp+qExgbdJi8R+CEbyFtCrsFFTdyJEqKwFSyhE77zZFC/uGNnm7A6RkhblKOoHcBqYLKWL1V4H0j3KgJVRrfu7eRMGwyxEydad/mCuyiiLEVv4BfyYo75jDuGNKppW6oJkZAaf5AmQcCEYvrBy7VkbP1vsIJ6f3v0x+Q9Du1HLObqkn5INec5y9kE9f7KjRNDPjXmEharkrYVAOs9PA2AnkPxFbKHxgiqgquzGFRShedqeTlmVWG0YePOdI1+2UYNJq7E4F8ZvqfdheaH8MpJ/JXv7sGM7Y0MqUq0GWNGBz6s/RdTkieuH0HiyeOMDsFK3hvPvDr+32XljMGO+Ee/IEnNF3+OL5/WNMwHbDqP2UlOlB7lYV1NEOzTtAUYq14B9C2ymF9ip/3HYGFH1U05uFEG+A5XpEiGPJ4hs7LOz1vZlNfC5yUCM4PQB24Aw3GEVXUMcS5inQtDQqT5KPd2wZ10OToI/vgmKG8EjKGUI+B7biMCOVaPQOrdIzAYPVuu9C8AKT3ovZUFy6Atw5+rt1sZkRTeCElC3/OKVPOwNFZPnBQleVHWhVd9oeVQAEBsVJ3mCNEGH+Lz7Tjoyk4rVJ80d6Hk7NjM9LKz/fdDbrpnGLvKkwSvYB4xIrtIfJIkRshpp3trf9+ohehlPHDtOCt4="
    - secure: "hQrKY/bc1hUQDLp8PFMMntdUFgF3udhaKkHh4jJRuWgcMttKiohGXS+A4lEd9r3pga3d2WYjr6D9fxF8oJOFhTHR+tilS8TridQ825P3MbvW/wf92SQJlnjpEbiMiyoj93eszxneSyq+NoHeQ0Iee0phLajOOvdUvZTgN0/RKH7484PYqN6S3Mp+qej+9Red7myj93DsNQu48d286fY5k3WnRPUjzFNuUGO/HbAGa7r+EhNBLCtXVpjavSpYWR1q+8TQcbt9Ehz3zSlgjZeybLeSPwWvlh+toO5Ai6v+iAoIzc7wVJ2MBlNLtZanfzTfRzJVJ9ErB/U9dOFPLEeSF2WIRrPFoEgKsi6/mK9pKxkX/tIZul1Z45EMhzpauibQu+uwsns069fPM4352qazDLFxzq7Jf/1skcrK0o6f4CFnZPb/nSXhK+OXRiiEw5RgEU9h93DKhBY1jIeH2YqAzW1UBvFatoVNwaBuK2vxM+2QktqBQbK8VVn94m8LptqcfxL1EHeYbRSamZjz3iy/AdVTqKhZypLGSkmkQFHSuQz4EoHmRE1byNq4HhTanc7HPglFJybiPuhRQZ7KMtG6Etz/6JgZEyWZ7SPQ8XnsDSOzyRovVomp0T5pd3kX/NhzKtDwXj71Zo1SvyluAT5ST7sOA3CqL6D2dAQDG9phoAQ="
    - secure: "J+e2di4bR7uOB4EVK8QvwuMzvpNmY38QbzxRiJ9/yLqYjRBh3VRnaxomxyCuWe9NwfBzUu1ab9QSV8mokpOLx59FyndNgOZBRZC+z1dWQ+hyP6c3Dz7GZOnFq+CndDLN+CeJ2Qzm6/Mso/PUkMLwzV3p4/MverUh0ckaeI4sSCCdg0mrwmMdbirCDJ33FPCkrjC02SWWzdVY8zfy9jNl2Eo43VAsr7xmvzOVrry/01WJyPke0IQ83pdzUAyy5IKsdis0ImLS1OUb8jhHoA866lFfw5FeFnM2mNjNWaFxO0omaMwte+64JzoMYlIp8S+nYSULrzMiN2Wew/IJUO3BTwNwflFyr114bC0PdecKdSNiHBUlpZNSStQLs/S1iZU48EkfgtC/hzQ/pUYvpHoAcTUgu+Vxzytw0FpIsKopV3orwO7h1Q+XA+vFXxOwtacSsQKO5HIlobX0pwVHP26gYaL1Wyxf3lnk/IZTEku46dmh5DHd1SMGl1CXoKSmnwJSUh59q1HCfSCog8gCKvYyZvVtZr5r4KzH4k3VMkmx0iBJYj65Stv8xp9zIKw/p4HoXJQFMV7ia1nlc7WftPtRz0NWdg8sniZrpHeBHQz5E+EB/82MfoTaXawFpGN8WwA1IGao/2IZkd6IC+HIWqVNykf499HwMxSsApEOkUxburw="

addons:
  apt:
    packages:
      - sshpass

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
  - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start --standalone 2>&1 &"
  - sleep 5

script:
  - echo "running tests"
  - grunt test
  - grunt protractor-firefox

after_success:
  - echo "deploying"
  - grunt build
  - tar -czf dist.tgz dist
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o stricthostkeychecking=no dist.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e scp -o stricthostkeychecking=no deploy.sh $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOSE $DEPLOY_PATH/deploy.sh
